# Translations template for neutron.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the neutron project.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version: Neutron\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-06-09 06:08+0000\n"
"PO-Revision-Date: 2014-05-29 07:49+0000\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: Portuguese (Brazil) (http://www.transifex.com/projects/p/"
"neutron/language/pt_BR/)\n"
"Language: pt_BR\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#: neutron/openstack/common/excutils.py:76
#, python-format
msgid "Original exception being dropped: %s"
msgstr "Exceção original sendo descartada: %s"

#: neutron/openstack/common/excutils.py:105
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr "Exceção não esperada ocorreu %d vez(es)... tentando novamente."

#: neutron/openstack/common/periodic_task.py:179
#, python-format
msgid "Error during %(full_task_name)s: %(e)s"
msgstr ""

#: neutron/openstack/common/service.py:188
msgid "Exception during rpc cleanup."
msgstr "Exceção durante limpeza de RPC."

#: neutron/openstack/common/service.py:276
msgid "Unhandled exception"
msgstr "Exceção não tratada"

#: neutron/openstack/common/db/api.py:72
msgid "DB exceeded retry limit."
msgstr ""

#: neutron/openstack/common/db/api.py:76
msgid "DB connection error."
msgstr ""

#: neutron/openstack/common/db/sqlalchemy/session.py:460
msgid "DB exception wrapped."
msgstr "Exceção de BD incluída."

#: neutron/openstack/common/middleware/notifier.py:40
#, python-format
msgid "An exception occurred processing the API call: %s "
msgstr ""

#: neutron/openstack/common/rpc/amqp.py:480
#: neutron/openstack/common/rpc/impl_zmq.py:286
msgid "Exception during message handling"
msgstr "Exceção durante a manipulação de mensagem"

#: neutron/openstack/common/rpc/common.py:88
msgid "Exception in string format operation"
msgstr "Exceção na operação de formato de sequência"

#: neutron/openstack/common/rpc/common.py:292
#, python-format
msgid "Returning exception %s to caller"
msgstr "Retornando exceção %s ao método de origem"

#: neutron/openstack/common/rpc/impl_kombu.py:156
msgid "Failed to process message ... skipping it."
msgstr "Falha ao processar mensagem...pulando ela."

#: neutron/openstack/common/rpc/impl_kombu.py:160
msgid "Failed to process message ... will requeue."
msgstr "Falha ao processar mensagem... Irá voltar para a fila."

#: neutron/openstack/common/rpc/impl_kombu.py:571
#, python-format
msgid ""
"AMQP server on %(hostname)s:%(port)d is unreachable: %(err_str)s. Trying "
"again in %(sleep_time)d seconds."
msgstr ""
"O servidor AMQP em %(hostname)s:%(port)d está inatingível: %(err_str)s. "
"Tentando novamente em %(sleep_time)d segundos."

#: neutron/openstack/common/rpc/impl_kombu.py:625
#: neutron/openstack/common/rpc/impl_qpid.py:575
#, python-format
msgid "Failed to declare consumer for topic '%(topic)s': %(err_str)s"
msgstr "Falha ao declarar consumidor para o tópico '%(topic)s': %(err_str)s"

#: neutron/openstack/common/rpc/impl_kombu.py:647
#: neutron/openstack/common/rpc/impl_qpid.py:594
#, python-format
msgid "Failed to consume message from queue: %s"
msgstr "Falha ao consumir mensagem da fila: %s"

#: neutron/openstack/common/rpc/impl_kombu.py:686
#: neutron/openstack/common/rpc/impl_qpid.py:629
#, python-format
msgid "Failed to publish message to topic '%(topic)s': %(err_str)s"
msgstr "Falha ao publicar mensagem no tópico '%(topic)s': %(err_str)s"

#: neutron/openstack/common/rpc/impl_qpid.py:191
msgid "Failed to process message... skipping it."
msgstr "Falha ao processar mensagem... ignorando-a."

#: neutron/openstack/common/rpc/impl_qpid.py:517
#, python-format
msgid "Unable to connect to AMQP server: %(e)s. Sleeping %(delay)s seconds"
msgstr ""
"Não é possível conectar ao servidor AMQP: %(e)s. Suspendendo em %(delay)s "
"segundos"

#: neutron/openstack/common/rpc/impl_qpid.py:602
msgid "Error processing message.  Skipping it."
msgstr "Erro ao processar mensagem. Ignorando-o."

#: neutron/openstack/common/rpc/impl_zmq.py:96
msgid "JSON serialization failed."
msgstr "Falha na serialização de JSON."

#: neutron/openstack/common/rpc/impl_zmq.py:195
msgid "ZeroMQ socket could not be closed."
msgstr ""

#: neutron/openstack/common/rpc/impl_zmq.py:339
msgid "RPC message did not include method."
msgstr "A mensagem de RPC não incluiu o método."

#: neutron/openstack/common/rpc/impl_zmq.py:476
msgid "Topic socket file creation failed."
msgstr "Falha na criação do arquivo de soquete do tópico."

#: neutron/openstack/common/rpc/impl_zmq.py:482
#, python-format
msgid ""
"Local per-topic backlog buffer full for topic %(topic)s. Dropping message."
msgstr ""
"Buffer de lista não processada por tópico local integral para o tópico "
"%(topic)s. Descartando mensagem."

#: neutron/openstack/common/rpc/impl_zmq.py:498
#, python-format
msgid "Required IPC directory does not exist at %s"
msgstr "Diretório IPC requerido não existe em %s"

#: neutron/openstack/common/rpc/impl_zmq.py:507
#, python-format
msgid "Permission denied to IPC directory at %s"
msgstr "Permissão negada para o doretório IPC em %s"

#: neutron/openstack/common/rpc/impl_zmq.py:510
msgid "Could not create ZeroMQ receiver daemon. Socket may already be in use."
msgstr ""
"Não foi possível criar o daemon receptor ZeroMQ. O soquete já pode estar em "
"uso."

#: neutron/openstack/common/rpc/impl_zmq.py:563
msgid "ZMQ Envelope version unsupported or unknown."
msgstr "Versão de Envelope ZMQ não suportada ou desconhecida."
